logging:
  level: INFO
  loggers:
    io.github.lusis: DEBUG
# by default, no configuration enables tracing for all paths but drops everything on the floor
opencensus:
# set enabled to false to fully disable it
#  enabled: false
  exporters:
    # options [logging, default, stackdriver]
    - type: logging
   # - type: stackdriver
      # projectId is used for the stackdriver exporter - optional
      # defaults are checked here: https://github.com/googleapis/google-cloud-java/blob/master/README.md#specifying-a-project-id
      #projectId:  test-project-1-XXXXXXXX
      # attributes are key/value strings applied as static attributes to all spans in StackDriver
      #attributes:
      #  project_name: ExampleApplication
  sampler:
    # options [never, always, probability]
    type: always
    # sampleRate is used for the probability sampler
    #sampleRate: 0.50
  # array of urls to trace - default is /*
  # paths:
  #  - "/example/ping"
  #  - "/example/client"